Add batch support

diff --git a/.github/workflows/sql-forge.yml b/.github/workflows/sql-forge.yml
--- a/.github/workflows/sql-forge.yml
+++ b/.github/workflows/sql-forge.yml
@@ -88,6 +88,19 @@ jobs:
       - name: Install sqlx-cli
         run: cargo install sqlx-cli --no-default-features --features native-tls,mysql,postgres,sqlite
 
+      - name: Install cargo-expand
+        run: cargo install cargo-expand
+
+      - name: cargo expand and compare with repo copy
+        run: |
+          cargo expand --test tests > tests/${{ matrix.db-type }}/tests_expanded.ci.rs
+          if ! diff -q tests/${{ matrix.db-type }}/tests_expanded.rs tests/${{ matrix.db-type }}/tests_expanded.ci.rs; then
+            echo "ERROR: tests/${{ matrix.db-type }}/tests_expanded.rs is outdated."
+            echo "Regenerate it by running in the rust service from the docker-compose file: sql-forge-test"
+            diff tests/${{ matrix.db-type }}/tests_expanded.rs tests/${{ matrix.db-type }}/tests_expanded.ci.rs
+            exit 1
+          fi
+
       - name: cargo check
         run: cargo check --tests
 
